### ISSUE TITLE
Can't use Feedbacks in Beta 3.0.0

### ISSUE THREAD

**Issue by Meldaro** [bitfocus/companion-module-lightware-lw3#10]
Hey, i would like to build myself a controller for a Lightware 8x8 Matrix, but can't use the Feedbacks to highlight the selected port until another port is selected. How can i do this?

Edit: Did i just see that @JeffreyDavidsz is just working on exactly that right now?

Edit 2: Got a workaround with a custom variable that gets set and a feedback based on that variable

**Comment by dnmeid** [comment]
Feedbacks are now reimplemented. Tested with MMX-8x8-HDMI-4K-A-USB20
