### ISSUE TITLE
Connection Problem to MX2 in Version 3.0.0+5917-beta-56c83cb0

### ISSUE THREAD

**Issue by Meldaro** [bitfocus/companion-module-lightware-lw3#11]
Now as the Feedbacks are implemented I wanted to clean my workaround up and do it right. Seems like this Version has a Problem with the Connections. Tested with Lightware MX2, Status says "unknown stopped after some seconds. The Connection works in version 5887.

**Comment by dnmeid** [comment]
Can you please tell me the version of the module which was working, you can find it on the top of the help page for the connection. It is always a little difficult to associate companion build numbers to module versions.

**Comment by dnmeid** [comment]
Please try again with version 2.03 of the module. It should fix some problems with MX2 matrices.
