### ISSUE TITLE
receive feedback not working

### ISSUE THREAD

**Issue by kaibueden** [bitfocus/companion-module-lightware-lw3#15]
error: received malformed connection status: CHG /MEDIA/XP/VIDEO.DestinationConnectionStatus=0;I2;I18;I18;I22;I22;I22;I24;I24;I17;I17;I18;I17;I5;I6;I1;I2;I14;I4;I7;I8;I6;I5;I4;

Companion 3.0.1 don't get any feedback of the Matrix via LW3.

**Comment by JaaHann** [comment]
For me the 'route' Feedback is not working in Companion 3.0.1+6068-stable-a05a9c89, connected to an MX2-24x24-HDMI20 with LW3.
Actions work fine as well as the select feedbacks.

**Comment by JaaHann** [comment]
Looks like the code doesn't take "unroutet" outputs into consideration when parsing messages.

`if (inputs[0].match(/^I\d+$/))` (index.js, L832)
This currently only checks for elements starting with an "I", followed by any number.
To also check for empty outputs, it should additionally check for elements that are "0" within the regular expression.
`if (inputs[0].match(/^(I\d+|0)$/))`

@kaibueden to resolve this issue for now, you could try to route any input to output 1 so it's not "0" and raising the error.
@josephdadams (or any other contributor) could you please fix this directly? I'm not familiar with pull requests, unfortunately. Thanks a lot!

**Comment by josephdadams** [comment]
I have made the change you suggested and pushed that into `v2.0.5`
