### ISSUE TITLE
LW3 loses names on I/O and can no longer be assigned in Companion 2.4.1 and later

### ISSUE THREAD

**Issue by ddouglassLuxMC** [bitfocus/companion-module-lightware-lw3#7]
We've had to revert/convert to the LW2 version to retain functionality on version 2.4.1 of 
![LW3](https://user-images.githubusercontent.com/81324368/231578944-c615f0ef-ba62-43c4-bc11-b89c932b6695.jpg)

**Comment by JeffreyDavidsz** [comment]
This works again in v3
